version: 2
jobs:
  # Build the base project directory (e.g. ~/package.json).
  build:
    docker:
      - image: circleci/node:8@sha256:01945cf325b27e0cc38ad7adae1567907d9729d56ff151e931aedd4aa91337d1
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Run security check.
      - run:
          name: Security check
          command: yarn security-check
      # Run the lint tool on the whole repository.
      - run:
          name: Lint
          command: yarn lint
      # Run the unit tests.
      - run:
          name: Unit tests
          command: yarn test

