version: 2
jobs:
  # Build the base project directory (e.g. ~/package.json).
  build:
    docker:
      - image: circleci/node:8@sha256:cc45ae6ca2a6ad316c360130c2115e6685aa240c4b23c917d5cd19066d3716d4
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Run security check.
      - run:
          name: Security check
          command: yarn security-check
      # Run the lint tool on the whole repository.
      - run:
          name: Lint
          command: yarn lint
      # Run the unit tests.
      - run:
          name: Unit tests
          command: yarn test

