version: 2
jobs:
  # Build the base project directory (e.g. ~/package.json).
  build:
    docker:
      - image: circleci/node:8@sha256:71ef306eb872eef41a5e308fec178430529cb5e24ff45254c1f6aa27f6039d7d
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Run security check.
      - run:
          name: Security check
          command: yarn security-check
      # Run the lint tool on the whole repository.
      - run:
          name: Lint
          command: yarn lint
      # Run the unit tests.
      - run:
          name: Unit tests
          command: yarn test

