version: 2

#
# Jobs
#

jobs:

  # This job builds the base project directory (e.g. ~/package.json)
  build:
    docker:
      - image: circleci/node:8@sha256:a79f5ee70874ce1f0e2d353323af1d6e3bdb0de1684068b8913102fdfb5dc68e
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  # This job runs the lint tool on the whole repository
  security-check:
    docker:
      - image: circleci/node:8@sha256:bf22ccaadca0cd6dc7019003eb6592163aa9edbdb0652128ca90e0af002bc055
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Security check
          command: yarn security-check

  # This job runs the lint tool on the whole repository
  lint:
    docker:
      - image: circleci/node:8@sha256:a79f5ee70874ce1f0e2d353323af1d6e3bdb0de1684068b8913102fdfb5dc68e
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint

  # runs the unit tests
  unit-test:
    docker:
      - image: circleci/node:8@sha256:a79f5ee70874ce1f0e2d353323af1d6e3bdb0de1684068b8913102fdfb5dc68e
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Unit tests
          command: npm run test

#
# Workflows
#

workflows:
  version: 2

  build_lint_test:
    jobs:
      - build

      - security-check:
          requires:
            - build
      - lint:
          requires:
            - build
      - unit-test:
          requires:
            - build
