version: 2

#
# Jobs
#

jobs:

  # This job builds the base project directory (e.g. ~/package.json)
  build:
    docker:
      - image: circleci/node:8@sha256:42a444578e730e3ac26f57223ead96db14a28fa3ad79e351964d7bedccd05f72
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  # This job runs security check
  security-check:
    docker:
      - image: circleci/node:8@sha256:42a444578e730e3ac26f57223ead96db14a28fa3ad79e351964d7bedccd05f72
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Security check
          command: yarn security-check

  # This job runs the lint tool on the whole repository
  lint:
    docker:
      - image: circleci/node:8@sha256:42a444578e730e3ac26f57223ead96db14a28fa3ad79e351964d7bedccd05f72
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint

  # runs the unit tests
  unit-test:
    docker:
      - image: circleci/node:8@sha256:42a444578e730e3ac26f57223ead96db14a28fa3ad79e351964d7bedccd05f72
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Unit tests
          command: npm run test

#
# Workflows
#

workflows:
  version: 2

  build_lint_test:
    jobs:
      - build

      - security-check:
          requires:
            - build
      - lint:
          requires:
            - build
      - unit-test:
          requires:
            - build
