version: 2

#
# Jobs
#

jobs:

  # This job builds the base project directory (e.g. ~/package.json)
  build:
    docker:
      - image: circleci/node:8@sha256:1e509cc328df81844a3eb85ead968a83f2057d0a9b74df637a59506bfccfa731
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  # This job runs the lint tool on the whole repository
  lint:
    docker:
      - image: circleci/node:8@sha256:1e509cc328df81844a3eb85ead968a83f2057d0a9b74df637a59506bfccfa731
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}              
      - run:
          name: Lint
          command: npm run lint

  # runs the unit tests
  unit-test:
    docker:
      - image: circleci/node:8@sha256:1e509cc328df81844a3eb85ead968a83f2057d0a9b74df637a59506bfccfa731
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Unit tests
          command: npm run test

#
# Workflows
#

workflows:
  version: 2

  build_lint_test:
    jobs:
      - build     

      - lint:     
          requires:
            - build
      - unit-test:     
          requires:
            - build
